test: final version

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -130,23 +130,22 @@ jobs:
           -m pytest -rf -vv --log-cli-level=INFO --show-capture=no \
           -n auto --timeout=300 \
           --first-test-file=tests/main/test_llm.py \
-          tests/main/test_task.py
-#          --first-test-file=tests/main/test_task.py
-#          --first-test-file=tests/main/test_llm_async.py \
-#          --first-test-file=tests/main/test_task_inf_loop.py \
-#          --first-test-file=tests/main/test_lance_doc_chat_agent.py \
-#          tests/main tests/extras/test_hf_embeddings.py tests/extras/test_fastembed_embeddings.py
+          --first-test-file=tests/main/test_task.py \
+          --first-test-file=tests/main/test_llm_async.py \
+          --first-test-file=tests/main/test_task_inf_loop.py \
+          --first-test-file=tests/main/test_lance_doc_chat_agent.py \
+          tests/main tests/extras/test_hf_embeddings.py tests/extras/test_fastembed_embeddings.py
       continue-on-error: true
 
-    - name: Debug coverage files
-      run: |
-        ls -la
-        ls -la .coverage.*
-        echo "Content of .coveragerc (if exists):"
-        cat .coveragerc || echo ".coveragerc not found"
-
-    - name: Combine parallel coverage data
-      run: poetry run coverage combine
+#    - name: Debug coverage files
+#      run: |
+#        ls -la
+#        ls -la .coverage.*
+#        echo "Content of .coveragerc (if exists):"
+#        cat .coveragerc || echo ".coveragerc not found"
+#
+#    - name: Combine parallel coverage data
+#      run: poetry run coverage combine
 
     - name: Retry FAILED tests ONLY with gpt-4 instead of gpt-4o
       id: second_test
@@ -157,14 +156,12 @@ jobs:
         poetry run coverage run  --append \
           -m pytest --m gpt-4 -rf --show-capture=no --timeout=300 \
           --first-test-file=tests/main/test_llm.py \
+          --first-test-file=tests/main/test_llm_async.py \
+          --first-test-file=tests/main/test_task_inf_loop.py \
+          --first-test-file=tests/main/test_task.py \
+          --first-test-file=tests/main/test_lance_doc_chat_agent.py \
           --lf --last-failed-no-failures none \
-          tests/main/test_task.py
-#          --first-test-file=tests/main/test_llm_async.py \
-#          --first-test-file=tests/main/test_task_inf_loop.py \
-#          --first-test-file=tests/main/test_task.py \
-#          --first-test-file=tests/main/test_lance_doc_chat_agent.py \
-#
-#          tests/main tests/extras/test_hf_embeddings.py tests/extras/test_fastembed_embeddings.py
+          tests/main tests/extras/test_hf_embeddings.py tests/extras/test_fastembed_embeddings.py
 
 
     - name: Generate final coverage report from all runs
