test: syntax

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -138,11 +138,11 @@ jobs:
       continue-on-error: true
 
     - name: Debug coverage files
-        run: |
-          ls -la
-          ls -la .coverage*
-          echo "Content of .coveragerc (if exists):"
-          cat .coveragerc || echo ".coveragerc not found"
+      run: |
+        ls -la
+        ls -la .coverage*
+        echo "Content of .coveragerc (if exists):"
+        cat .coveragerc || echo ".coveragerc not found"
 
     - name: Combine parallel coverage data
       run: poetry run coverage combine .coverage*
